key: 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
dry_run: false

model_config:
  model: "hf/meta-llama/Llama-2-7b-chat-hf"
  type: CHAT
  conv_template: "llama-2"

  model_loader: HF
  torch_dtype: BFLOAT16
  quant_file: null
  tokenizer_name: meta-llama/Llama-2-7b-chat-hf
  trust_remote_code: true
  use_auth_token: true

hydra:
  job:
    chdir: false

  callbacks:
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback
